---
title: "Code Part"
author: "Shangshang Wang"
date: "5/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)
```

```{r}
load("msts_weekly_2010.RData")
load("weekly_2010_ts.RData")
```

```{r}
msts_weekly_2010 <- msts(msts_weekly_2010,seasonal.periods = 52, start = 2010,ts.frequency = 52)
bestfit <- list(aicc=Inf)
for (i in 1:26) {
  fit_four<-auto.arima(msts_weekly_2010,seasonal = F,lambda = 0,xreg = fourier(msts_weekly_2010,K = i))
  if(fit_four[["aicc"]] < bestfit[["aicc"]]){
    bestfit <- fit_four
    besti <- i
  }
}
```

```{r}
fc <- forecast(bestfit, xreg = fourier(msts_weekly_2010, K = besti, h = 52))

autoplot(fc)
checkresiduals(bestfit)
summary(bestfit)

predict(fc,xreg = fourier(msts_weekly_2010, K = besti, h = 52),n.ahead = 52)

```

```{r}

coef_df <- data.frame(coef = NA, Aic = NA, seasonal = NA,pval = NA)
l = 1
for (i in 0:1) {
  for (j in 0:4) {
    for (k in 0:4) {
      fit <-Arima(weekly_2010_ts, order = c(j,i,k), seasonal = c(0,0,1))
      #summary(fit)
      fc <- forecast(fit,h = 26)
      coef_df[l,"coef"]<-toString(c(j, i, k))
      coef_df[l,"Aic"]<-fit$aic
      coef_df[l,"pval"]<-Box.test(fit$residuals)$p.value
      
      l = l + 1
    }
  }
}
```


```{r}

fit1 <- Arima(weekly_2010_ts, order = c(4,1,4), seasonal = c(0,0,1))
forecast(fit1,h = 52) %>% autoplot()
#SMALL INCRE

fit2 <- Arima(weekly_2010_ts, order = c(3,1,1), seasonal = c(0,0,1))
forecast(fit2,h = 52) %>% autoplot()
#DECREASE

fit3 <- Arima(weekly_2010_ts, order = c(0,1,4), seasonal = c(0,0,1))
forecast(fit3,h = 52) %>% autoplot()
#DECREASE

fit4 <- Arima(weekly_2010_ts, order = c(1,1,4), seasonal = c(0,0,1))
forecast(fit4,h = 52) %>% autoplot()

fit5 <- Arima(weekly_2010_ts, order = c(4,0,1), seasonal = c(0,0,1))
forecast(fit5,h = 52) %>% autoplot()

fit6 <- Arima(weekly_2010_ts, order = c(4,1,1), seasonal = c(0,0,1))
forecast(fit6,h = 52) %>% autoplot()
#decr

fit7 <- Arima(weekly_2010_ts, order = c(3,1,2), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()

fit7 <- Arima(weekly_2010_ts, order = c(2,1,4), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()

fit7 <- Arima(weekly_2010_ts, order = c(4,1,2), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()

fit7 <- Arima(weekly_2010_ts, order = c(4,1,3), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()

fit7 <- Arima(weekly_2010_ts, order = c(3,1,4), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()

fit7 <- Arima(weekly_2010_ts, order = c(2,1,3), seasonal = c(0,0,1))
forecast(fit7,h = 52) %>% autoplot()
```

```{r}
load("crime_2020[which(is.na(crime_2020$New_Category)), ].RData")

crime_2020[which(is.na(crime_2020$New_Category)), ]$New_Category <- NA

na_indec <- which(is.na(crime_2020$New_Category))

for (i in na_indec){
  if(grepl("BURGLARY|THEFT|ARSON|MONEY|CHECK|TRESPASSING|PURSE|PUNCO|COMPUTER|EXTORTION|PICKPOCKET|CREDIT",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Property"
    #print(1)
    next
  }else if(grepl("SEX|RAPE|LEWD|INDECENT|PIMPING|ORAL",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Sex"
    #print(2)
    next
  }else if(grepl("VANDALISM|BOMB|PEACE",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Vandalism"
    #print(3)
    next
  }else if(grepl("INTIMATE",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Domestic_Violence"
    #print(4)
    next
  }else if(grepl("CHILD",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Child Abuse"
    #print(5)
    next
  }else if(grepl("VIOLENCE|ASSAULT|WEAPON|GUN|ROBBERY|HOMICIDE|OFFENSE|BATTERY|KIDNAPPING|FIRED",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Violence"
    #print(6)
    next
  }else if(grepl("DRUG|NARCOTIC|DRUNK|ALCOHOL|LIQUOR",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Drink_Drug"
    #print(7)
    next
  }else if(grepl("VEHICLE|BOAT|TRAFFIC|DRIVE|DRIVING|BICYCLE|BIKE",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Traffic"
    #print(8)
    next
  }else if(grepl("DISORDER|MENTAL|VAGRANCY|GAMBL|MISDEMEANOR|PROWLER",crime_2020[i,"Crm Cd Desc"])){
    crime_2020$New_Category[i] <- "Misdemeanor"
    #print(9)
    next
  }
  
}
    

```

```{r}
crime_2020[which(is.na(crime_2020$New_Category)), "New_Category"]<-"Other"
```

```{r}
bestfit
predict(bestfit)
```

```{r}
library(ggplot2)
library(dplyr)

unemployment <- c(232223, 238219, 320548, 1185820)
date <- c(202001, 202002, 202003, 202004)

df_new <- cbind(unemployment, date)
df_new <- as.data.frame(df_new)
df_new
ggplot(df_new, aes(x = date, y = unemployment)) + theme(
  title = element_text(size=12, face='bold'),
panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), panel.background=element_rect(fill = "white")) +  ggtitle("2020 Jan - April Unemployment Number plot for LA County") + geom_smooth(color = "salmon", size = 2)




```



