---
title: "Untitled"
author: "Yan Sun(204768204)"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import packages

```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(lubridate)
library(xts)
library(forecast)
```


## import dataset
```{r}
Crime_Data_from_2020_to_Present <- read_csv("Crime_Data_from_2020_to_Present.csv", col_types = cols(`DATE OCC` = col_datetime(format = "%m/%d/%Y %H:%M:%S AM")))
date_table <- read_csv("date_table.csv")
```


## Trend Analysis

```{r}
Crime_Data_from_2020_to_Present$`DATE OCC`<- Crime_Data_from_2020_to_Present$`DATE OCC` %>% as.Date()


ggplot(date_table) + 
  geom_bar(aes(x = date_dt, y = total_cases/45),fill = "#F8766D",alpha = 0.8,stat = "identity") +
  theme(axis.text.y = element_blank()) + 
  theme_classic()+
  scale_y_continuous(limits = c(0,700), breaks = c(seq(0,700,150)), sec.axis = sec_axis(~.*45, name = "Cumulative Covid-19 Cases", breaks = seq(0,30000,10000)))+
  stat_count(geom='line', aes(x = `DATE OCC`, y=..count..),color = "#00BFC4",data = Crime_Data_from_2020_to_Present[Crime_Data_from_2020_to_Present$`DATE OCC`>as.Date("2020-01-01"),]) +
  xlab("Year of 2020") + ylab("Total Crime Cases") +
  ggtitle("Total Crime Cases vs Total Covid-19 Cases in LA County", subtitle = "from 2020/01/01 to 2020/05/04") 
  
```

## Crime category analysis

```{r}
Crime_Data_from_2020_to_Present$`Part 1-2` <- Crime_Data_from_2020_to_Present$`Part 1-2` %>% as.factor()
Crime_Data_from_2020_to_Present %>% group_by(`DATE OCC`,`Part 1-2`) %>% summarise(n = n()) %>% ggplot() + geom_line(aes(x = `DATE OCC`, y = n, color = `Part 1-2`))

Crime_Data_from_2010_to_2019$`Part 1-2` <- Crime_Data_from_2010_to_2019$`Part 1-2`%>% as.factor()

Crime_Data_from_2010_to_2019 %>% group_by(`DATE OCC`,`Part 1-2`) %>% summarise(n = n()) %>% filter(n<750)%>% ggplot() + geom_line(aes(x = `DATE OCC`, y = n, color = `Part 1-2`))

date_2019<- Crime_Data_from_2010_to_2019 %>% group_by(`DATE OCC`) %>% summarise(n = n())
date_2019 <- date_2019$`DATE OCC`
trim_Crime_Data_from_2010_to_2019 <- Crime_Data_from_2010_to_2019 %>% select(`DATE OCC`,`Part 1-2`)
trim_Crime_Data_from_2010_to_2019 <- trim_Crime_Data_from_2010_to_2019 %>% mutate(Month = format(`DATE OCC`, "%Y-%m"))
monthly <- trim_Crime_Data_from_2010_to_2019 %>% group_by(`Month`,`Part 1-2`) %>% summarise(n = n()) 
monthly$Month <- as.yearmon(monthly$Month)

ggplot(monthly) + geom_line(aes(x = Month, y = n, color =`Part 1-2`))

trim_Crime_Data_from_2020 <- Crime_Data_from_2020_to_Present %>% select(`DATE OCC`,`Part 1-2`)
total_crime <- rbind(trim_Crime_Data_from_2010_to_2019,trim_Crime_Data_from_2020)



```

```{r}
ggplot(Crime_Data_from_2020_to_Present)+
  stat_count(geom='line', aes(x = `DATE OCC`, y=..count../alpha, color = "Total crime"),data =  Crime_Data_from_2020_to_Present[Crime_Data_from_2020_to_Present$`DATE OCC`>as.Date("2020-01-01"),]) +
  xlab("Year of 2020") + ylab("Crime Cases") +
ggtitle("Crime Cases Decomposition in LA County", subtitle = "from 2020-01-01 to 2020-05-04") + geom_line(aes(x = `DATE OCC`, y = n, color = `Part 1-2`), data = (data = Crime_Data_from_2020_to_Present[Crime_Data_from_2020_to_Present$`DATE OCC`>as.Date("2020-01-01"),] %>% group_by(`DATE OCC`,`Part 1-2`) %>% summarise(n = n()/alpha))) + scale_color_discrete(name = "Crime Type", breaks = c("1","2","Total crime"),labels = c("PART I","PART II","Total Crime"))+theme_classic()
  
```



```{r}
CATEGORY_NEW <- list(
  Property = c("BURGLARY","LARCENY THEFT","GRAND THEFT AUTO","ARSON","FEDERAL OFFENSES WITH MONEY","FRAUD AND NSF CHECKS"),
  Traffic = c("VEHICLE / BOATING LAWS","ACCIDENTS TRAFFIC/VEH./BOAT","DRUNK DRIVING VEHICLE / BOAT"), 
  Violence = c("AGGRAVATED ASSAULT","NON-AGGRAVATED ASSAULTS","WEAPON LAWS","ROBBERY","CRIMINAL HOMICIDE","FEDERAL OFFENSES W/O MONEY"),
  Vandalism = c("VANDALISM"),
  Domestic_Violence = c("OFFENSES AGAINST FAMILY","SUICIDE AND ATTEMPT"),
  Drink_Drug = c("NARCOTICS","DRUNK / ALCOHOL / DRUGS","LIQUOR LAWS"),
  Sex = c("SEX OFFENSES FELONIES","SEX OFFENSES MISDEMEANORS","FORCIBLE RAPE"),
  Misdemeanor = c("DISORDERLY CONDUCT","VAGRANCY","GAMBLING","MISDEMEANORS MISCELLANEOUS","MENTALLY ILL","FELONIES MISCELLANEOUS"),
  Other = c("RECEIVING STOLEN PROPERTY","JUVENILE NON-CRIMINAL","PERSONS MISSING","FORGERY","PERSONS DEAD","ACCIDENTS MISCELLANEOUS","COMMITMENTS","MISCELLANEOUS NON-CRIMINAL","WARRANTS")
  )

write_label <- function(cat){
  for (i in 1:9){
    if ( cat %in% CATEGORY_NEW[[i]]){
      return(names(CATEGORY_NEW)[i])
      break
    }
  }
  return("na")
}

labels <- sapply(PART_I_AND_II_CRIMES_MIS$CATEGORY,write_label)
labels_v <- unlist(labels)
PART_I_AND_II_CRIMES_MIS$New_Category <- labels_v
PART_I_AND_II_CRIMES_MIS %>% filter(New_Category =="na")

labels2 <- sapply(CRIMES_2019_month_MIS$CATEGORY,write_label)
labels2_v <- unlist(labels2)
CRIMES_2019_month_MIS$New_Category <- labels2_v
CRIMES_2019_month_MIS %>% filter(New_Category =="na")



find_dm <- grepl("DOMESTIC|Domestic",PART_I_AND_II_CRIMES_MIS$STAT_DESC)
PART_I_AND_II_CRIMES_MIS[find_dm,"New_Category"]<-"Domestic_Violence"

find_dm2 <- grepl("DOMESTIC|Domestic",CRIMES_2019_month_MIS$STAT_DESC)
CRIMES_2019_month_MIS[find_dm2,"New_Category"]<-"Domestic_Violence"

find_ch <- grepl("CHILD|CHILDREN|Children",PART_I_AND_II_CRIMES_MIS$STAT_DESC)
PART_I_AND_II_CRIMES_MIS[find_ch,"New_Category"]<- "Child Abuse"

find_ch2 <- grepl("CHILD|CHILDREN|Children", CRIMES_2019_month_MIS$STAT_DESC)
CRIMES_2019_month_MIS[find_ch2,"New_Category"] <- "Child Abuse"

```


```{r}
PART_I_AND_II_CRIMES_MIS %>% group_by(New_Category,INCIDENT_DATE)%>% summarise(count = n())%>% ggplot(aes(x = INCIDENT_DATE)) + geom_line(aes(y = count,color = New_Category))+ ggtitle("Number of Different Crimes by Day",subtitle = "from 2020-03-19 to 2020-05-04") + xlab("Year of 2020")+ylab("Count")+scale_color_brewer(palette = "RdYlGn")+theme_classic()+scale_x_date(labels = NULL)

CRIMES_2019_month_MIS %>% group_by(New_Category,INCIDENT_DATE)%>% summarise(count = n())%>% ggplot(aes(x = INCIDENT_DATE)) + geom_line(aes(y = count,color = New_Category))+ ggtitle("Number of Different Crimes by Day",subtitle = "from 2019-03-19 to 2019-05-04") + xlab("Year of 2019")+ylab("Count")+scale_color_brewer(palette = "RdYlGn")+theme_classic()+scale_x_date(labels = NULL)
```

```{r}
df_1 <- PART_I_AND_II_CRIMES_MIS %>% select(New_Category)
df_1$year <- 2020
df_2 <- CRIMES_2019_month_MIS %>% select(New_Category) 
df_2$year <- 2019
df_3 <- rbind(df_1,df_2)
df_3$year <- as.factor(df_3$year)
df_3 %>% ggplot() +geom_bar(aes(x = New_Category, fill = year),position = "dodge") + theme(axis.text.x = element_text(angle = 45, hjust = 1),panel.background = element_blank(),panel.grid.major = element_line(color = "grey90"))+scale_fill_brewer(palette = "RdYlGn") + xlab("Crime Types") + ggtitle("Number Comparison 2019 vs 2020",subtitle = "From March 19 to May 04")
df_3 %>% ggplot(aes(x = year, fill =New_Category)) + geom_bar(position = "fill",width = 0.75)+ scale_y_continuous(labels = scales::percent)+scale_fill_brewer(palette = "RdYlGn")+theme_classic()+ggtitle("Proportion Comparison 2019 vs 2020",subtitle = "From March 19 to May 04") + ylab("Proportion")
```


```{r}
crim_code <- list(Property = NA, Traffic = NA, Violence = NA, Vandalism = NA, Domestic_Violence = NA, Drink_Drug = NA, Sex = NA, Misdemeanor = NA, Other = NA)
crim_code$Violence <- CRIMES_2019_month_MIS %>% filter(New_Category=="Violence") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Property <- CRIMES_2019_month_MIS %>% filter(New_Category=="Property") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Traffic <- CRIMES_2019_month_MIS %>% filter(New_Category=="Traffic") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Vandalism <- CRIMES_2019_month_MIS %>% filter(New_Category=="Vandalism") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Domestic_Violence <- CRIMES_2019_month_MIS %>% filter(New_Category=="Domestic_Violence") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Drink_Drug <- CRIMES_2019_month_MIS %>% filter(New_Category=="Drink_Drug") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Sex <- CRIMES_2019_month_MIS %>% filter(New_Category=="Sex") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Misdemeanor <- CRIMES_2019_month_MIS %>% filter(New_Category=="Misdemeanor") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
crim_code$Other <- CRIMES_2019_month_MIS %>% filter(New_Category=="Other") %>% select(STAT) %>% unlist() %>% as.integer() %>% unique
```

## Fit Category for County data
```{r}
crime_2010 <- Crime_Data_from_2010_to_2019 %>% select(`DATE OCC`,`Crm Cd`,`Crm Cd Desc`)
crime_2020 <- Crime_Data_from_2020_to_Present %>% select(`DATE OCC`,`Crm Cd`,`Crm Cd Desc`)
total_crime <- rbind(crime_2010,crime_2020)
find_cd <- function(cd){
  for (i in 1:9){
    if(cd %in% crim_code[[i]]){
      return(names(crim_code)[i])
      break
    }else{
      return("na")
    }
  }
}
total_crime$New_Category <- NA
for (i in 6:nrow(total_crime)){
  if(grepl("BURGLARY|THEFT|ARSON|MONEY|CHECK",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Property"
    #print(1)
    next
  }else if(grepl("VEHICLE|BOAT|TRAFFIC|DRIVE|DRIVING",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Traffic"
    #print(2)
    next
  }else if(grepl("VANDALISM",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Vandalism"
    #print(3)
    next
  }else if(grepl("INTIMATE",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Domestic_Violence"
    #print(4)
    next
  }else if(grepl("CHILD",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Child Abuse"
    #print(5)
    next
  }else if(grepl("VIOLENCE|ASSAULT|WEAPON|GUN|ROBBERY|HOMICIDE|OFFENSE",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Violence"
    #print(6)
    next
  }else if(grepl("DRUG|NARCOTIC|DRUNK|ALCOHOL|LIQUOR",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Drink_Drug"
    #print(7)
    next
  }else if(grepl("SEX|RAPE",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Sex"
    #print(8)
    next
  }else if(grepl("DISORDER|MENTAL|VAGRANCY|GAMBL|MISDEMEANOR",total_crime[i,"Crm Cd Desc"])){
    total_crime$New_Category[i] <- "Misdemeanor"
    #print(9)
    next
  }
    
}
prop<- total_crime %>% grepl("BURGLARY|THEFT|ARSON|MONEY|CHECK",`Crm Cd Desc`)
total_crime[prop,"New_Category"] <- "Property"

total_crime <- total_crime %>% filter(grepl("VEHICLE|BOAT|TRAFFIC|DRIVE|DRIVING",`Crm Cd Desc`),New_Category!="Property") %>% mutate(New_Category = "Traffic")

total_crime <- total_crime %>% filter(grepl("VANDALISM",`Crm Cd Desc`)) %>% mutate(New_Category = "Vandalism")

total_crime <- total_crime %>% filter(grepl("INTIMATE",`Crm Cd Desc`)) %>% mutate(New_Category = "Domestic_Violence")

total_crime <- total_crime %>% filter(grepl("CHILD",`Crm Cd Desc`)) %>% mutate(New_Category = "Child Abuse")

total_crime <- total_crime %>% filter(grepl("VIOLENCE|ASSAULT|WEAPON|GUN|ROBBERY|HOMICIDE|OFFENSE",`Crm Cd Desc`),New_Category!="Child Abuse", New_Category!="Domestic_Violence") %>% mutate(New_Category = "Violence")

total_crime <- total_crime %>% filter(grepl("DRUG|NARCOTIC|DRUNK|ALCOHOL|LIQUOR",`Crm Cd Desc`)) %>% mutate(New_Category = "Drink_Drug")

total_crime <- total_crime %>% filter(grepl("SEX|RAPE",`Crm Cd Desc`)) %>% mutate(New_Category = "Sex")

total_crime <- total_crime %>% filter(grepl("DISORDER|MENTAL|VAGRANCY|GAMBL|MISDEMEANOR",`Crm Cd Desc`)) %>% mutate(New_Category = "Misdemeanor")

View(total_crime)
```

```{r}
crime_2010 <- Crime_Data_from_2010_to_2019$`DATE OCC`
crime_2010<- data.frame(date = crime_2010,dummy = 1)
crime_2010 <- crime_2010 %>% group_by(date) %>% summarise(Frq = sum(dummy))
omit_crime_2010 <- crime_2010[crime_2010$Frq<1000,]
plot(omit_crime_2010)
daily_crime_2010_xts <- as.xts(omit_crime_2010$Frq,order.by = omit_crime_2010$date, start = c(2010,1,1))
plot(weekly_crime_2010_xts)
weekly_2010_xts <- apply.weekly(weekly_crime_2010_xts,colMeans) 
weekly_2010.df <- data.frame(date = index(weekly_2010_xts),count = NA)
weekly_2010.df$count <- weekly_2010_xts%>%as.data.frame()
weekly_2010_ts <- ts(weekly_2010.df$count, 
   freq=365.25/7, 
   start= decimal_date(ymd(weekly_2010.df[1, 1])))
weekly_2010_ts %>% decompose() %>% autoplot()
weekly_2010_xts %>% acf(lag.max = 100) %>% plot()
```

```{r}
tsstationary = diff(weekly_2010_ts, differences=1,lag = 52) %>% diff()
adf.test(tsstationary)
library(fUnitRoots)
urkpssTest(tsstationary, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
plot(decompose(tsstationary))
seasadj(decompose(weekly_2010_ts)) %>% decompose %>% plot()
```
```{r}
ggseasonplot(weekly_2010_ts,polar = TRUE)
```

```{r}
monthly_2010_xts <- apply.monthly(daily_crime_2010_xts,colMeans) 
plot(monthly_2010_xts)
monthly_2010.df <- data.frame(date = index(monthly_2010_xts),count = NA)
monthly_2010.df$count <- monthly_2010_xts%>%as.data.frame()
monthly_2010_ts <- ts(monthly_2010.df$count,
   frequency=12,start = c(2010,01))
monthly_2010_ts  %>% autoplot()
ggseasonplot(monthly_2010_ts,polar = TRUE) +scale_color_brewer(palette = "Spectral") + ggtitle("Seaonal plot of Total Crime Cases by Year")+theme(panel.background = element_blank(),panel.grid.major = element_line(color = "grey90"))
```


```{r}
save(msts_weekly_2010,file = "msts_weekly_2010.RData")
msts_weekly_2010 <- msts(weekly_2010_ts,seasonal.periods = c(4,12,52),start = 2010,ts.frequency = 52)
msts_weekly_2010 %>% mstl() %>% autoplot()
```

```{r}
msts_weekly_2010 %>% stlf() %>% checkresiduals()
```




```{r}
msts_weekly_2010_2 <- msts(weekly_2010_ts,seasonal.periods = c(52,52*5),start = 2010,ts.frequency = 52)
msts_weekly_2010_2 %>% mstl() %>% autoplot()

fit_four2<-auto.arima(msts_weekly_2010_2,seasonal = F,lambda = 0,xreg = fourier(msts_weekly_2010_2,K = c(10,10)))
summary(fit_four2)
checkresiduals(fit_four2)
fit_four2 %>% forecast(xreg = fourier(msts_weekly_2010_2,K = c(10,10)),h = 5*52) %>% autoplot() 
```


```{r}
fit <- auto.arima(weekly_2010_xts,stationary = FALSE,seasonal = TRUE,stepwise = FALSE,allowdrift = TRUE,approximation = FALSE)

weekly_2010_xts %>% diff(lag = 52) %>% ggtsdisplay()

fit <-Arima(weekly_2010_ts,order = c(0,1,4),seasonal = c(0,1,1))
summary(fit)
fc <- forecast(fit,h = 26)
autoplot(fc)
checkresiduals(fit)
```


## Model Selection

```{r}
crime_2010 <- Crime_Data_from_2010_to_2019$`DATE OCC`
crime_2020 <- Crime_Data_from_2020_to_Present$`DATE OCC`
total_crime <- c(crime_2010,crime_2020)
total_crime <- data.frame(date = total_crime,dummy = 1)
total_crime <- total_crime %>% group_by(date) %>% summarise(Freq = sum(dummy))
plot(total_crime)
#Delete outliers in the first day of every year
omit_total_crime <- total_crime[total_crime$Freq<1000,]
plot(omit_total_crime)
#Delete data on 5/4 because of incomplete record
omit_total_crime <- omit_total_crime[-nrow(omit_total_crime),]
plot(omit_total_crime)

crime_xts <- as.xts(omit_total_crime$Freq, order.by = omit_total_crime$date)
plot(crime_xts)

apply.weekly(crime_xts,colMeans) %>% as.xts(
) %>% acf(lag.max = 150)
apply.weekly(crime_xts,colMeans) %>% as.xts(
) %>% pacf(lag.max = 100)

apply.weekly(crime_xts,colMeans) %>% as.xts(
) %>% plot()

```

```{r}
weekly <- apply.weekly(crime_xts,colMeans) %>% as.xts()
adf.test(weekly_diff)
fit <- Arima(weekly,order = c(5,0,2))
fit <- auto.arima(weekly)
summary(fit)
  #checkresiduals(fit)
  fc <- forecast(fit,h = 52)
  plot(fc)
```


```{r}
weekly_diff <- apply.weekly(crime_xts,colMeans) %>% diff(lag = 4) %>% na.omit()%>% as.xts()
library(tseries)
adf.test(weekly_diff)
acf(weekly_diff)
pacf(weekly_diff)
N <- nrow(weekly_diff)
fit <- auto.arima(weekly_diff[-((N-1):N)],stepwise = FALSE, approximation = FALSE)
fit <- Arima(weekly,order = c(1,0,0),seasonal = list(order = c(0,0,1),period = 52))
summary(fit)
  #checkresiduals(fit)
  fc <- forecast(fit,h = 26)
  autoplot(fc)
  
checkresiduals(fit)
```

```{r}
N <- nrow(weekly)
fit <- Arima(weekly[1:N,],order = c(1,0,0),seasonal = list(order = c(0,0,1),period = 12))
summary(fit)
  #checkresiduals(fit)
  fc <- forecast(fit,h = 52)
  autoplot(fc)
  
checkresiduals(fit)
predict(fit,n.ahead = 26)
```

```{r}
plot(weekly)
lines(fc$fitted)
fitted <- fc$fitted
fitted <- xts(fitted, order.by = index(weekly))
cbind(fitted,weekly) %>% plot(col = c("red","blue"))
```


```{r}
save(PART_I_AND_II_CRIMES_MIS,file = "crime_april_2020.RData")
save(CRIMES_2019_month_MIS, file = "crime_april_2019.RData")
load("crime_2020_new.RData")
load("bestfit_new.RData")
```


##Prediction 52 weeks

```{r}
msts_weekly_2010 <- msts(weekly_2010_ts,seasonal.periods = 52,start = c(2010,01,02),ts.frequency = 52)
fc <- forecast(bestfit,
  xreg=fourier(msts_weekly_2010, K=12,h = 78),n.ahead =78)
autoplot(fc)

predictted_52_weeks_2020 <- predict(fc,xreg=fourier(msts_weekly_2010, K=12, h=78),n.ahead = 78)
startDate <- as.Date("2020-01-01")
weeklyDate<-c(startDate)
for (i in 1:(78)){
  weeklyDate = append(weeklyDate,startDate+i*7)
}
weeklyPrediction <- data.frame(weeklyDate = weeklyDate[-1],predictMean = predictted_52_weeks_2020$mean)

weeklyPrediction %>% ggplot() + geom_line(aes(x = weeklyDate, y = predictMean))
#predictted_52_weeks_2020 %>% ggplot() %>% geom_smooth()
```

```{r}
crime_lockdown <- crime_2020[crime_2020$`DATE OCC`>"2020-03-18"&crime_2020$`DATE OCC`<"2020-05-04","DATE OCC"]
crime_lockdown<-data.frame(date = crime_lockdown,dummy = 1)
colnames(crime_lockdown)[1]<-"date"
crime_lockdown <- crime_lockdown %>% group_by(date) %>% summarise(Frq = sum(dummy))
daily_crime_lockdown_xts <- as.xts(crime_lockdown$Frq,order.by = crime_lockdown$date,start = c(2020,03,18))
plot(daily_crime_lockdown_xts)
daily_crime_lockdown_xts %>% ggtsdisplay()
fit_lockdown <- auto.arima(daily_crime_lockdown_xts)
summary(fit_lockdown)
checkresiduals(fit_lockdown)
fc_days <- as.Date("2020-07-31") - as.Date("2020-05-04")
fc_lockdown <- forecast(fit_lockdown,h = fc_days)
autoplot(fc_lockdown)
forecast(fc_lockdown,h = fc_days) %>% autoplot()

```

```{r}
inter <- data.frame(x = 1:10,y = NA)
p <-predict(fc_lockdown,h = 10)
inter$y<- predict(fc_lockdown,h = 10)$mean
m <-lm(y~log(x),data = inter[1:10,])
pp <- data.frame(x = 11:88)
pp$y <- predict(m,pp,se.fit = TRUE)$fit
inter$y <- inter$y %>% as.numeric()
plot(rbind(inter,pp))
```


```{r}
predictted_lockdown <- predict(fit_lockdown,fc_days)
next_day<- as.Date("2020-05-04")
future_july <-c()
for(i in 1:fc_days){
  future_july <- append(future_july,next_day+i)
}

lockdown_prediction <- data.frame(date = future_july,prediction = predictted_lockdown$pred)
lockdown_prediction %>% ggplot() + geom_line(aes(x = date, y = prediction)) + geom_line(aes(x = date,y = Frq),data = crime_lockdown)+ geom_line(aes(x = weeklyDate, y = predictMean),data = weeklyPrediction)

weeklyPrediction_july <- weeklyPrediction[weeklyPrediction$weeklyDate>"2020-07-31",]
lockdown_prediction$period <- "Extended Lockdown"
crime_lockdown$perid <- "Lockdown"
weeklyPrediction_july$period <- "Reopen"
colnames(weeklyPrediction_july) <-colnames(lockdown_prediction)
colnames(crime_lockdown)<-colnames(lockdown_prediction)


before_lockdown <- crime_2020[crime_2020$`DATE OCC`<"2020-03-18","DATE OCC"]
before_lockdown<-data.frame(date = before_lockdown,dummy = 1)
colnames(before_lockdown)[1]<-"date"
before_lockdown <- before_lockdown %>% group_by(date) %>% summarise(Frq = sum(dummy))
before_lockdown$period <-"Before Lockdown"
colnames(before_lockdown)<-colnames(lockdown_prediction)

final_prediction <- rbind(before_lockdown,crime_lockdown,lockdown_prediction,weeklyPrediction_july)

final_prediction %>% ggplot() + geom_line(aes(x = date, y = prediction, color = period))
```


```{r}
lockd_ts <- lockdown_prediction %>% select(date,prediction) %>% as.ts(prediction,order.by = lockdown_prediction$date,start = c(2020,05,05))
lockd_msts <- msts(lockd_ts,seasonal.periods = 365, start = c(2020,05,05))

rwf(lockdown_prediction$prediction,drift = TRUE,h = 78)
autoplot(rwf(lockdown_prediction$prediction[4:15],drift = TRUE,h = 84))
new_model <- rwf(lockdown_prediction$prediction[4:15],drift = TRUE,h = 84)
drift <- predict(new_model,n.ahead = 84)
new_lock_proj<-data.frame(date = lockdown_prediction$date,prediction = NA)
new_lock_proj$prediction[1:4]<-lockdown_prediction$prediction[1:5]
new_lock_proj$prediction[5:88]<-drift$mean

new_lock_proj$period <-"Reopen"
weeklyPrediction_july <- weeklyPrediction[weeklyPrediction$weeklyDate>"2020-07-31",]
weeklyPrediction_july$period <- "Reopen"
weeklyPrediction_july$date <-weeklyPrediction_july$date-3
colnames(weeklyPrediction_july) <- colnames(new_lock_proj)
crime_lockdown$period <- "Lockdown"
before_lockdown<-before_lockdown[-1,]
final_prediction1 <- rbind(before_lockdown,crime_lockdown)
final_prediction2 <- rbind(new_lock_proj,weeklyPrediction_july)

hist_avg <- weekly_2010.df$count %>% unlist() %>% as.numeric () %>% mean()

ggplot() + geom_line(aes(x = date, y = prediction, color = period),data = final_prediction1)+geom_smooth(aes(x = date, y = prediction, color = period),method = "loess",data = final_prediction2)+geom_hline(aes(yintercept = hist_avg),linetype = "dashed",color = "red") +theme_classic() +geom_text(aes(y = hist_avg,label = "Historical Average = 575.9981",x = as.Date("2020-01-01"),hjust = -1,vjust = 2),color = "red",alpha = 0.8)+ggtitle("Total Crime Cases Forecasting in LA County")+scale_x_date(date_breaks = "1 month")+theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


